<?php
$definitions = ['projects'=>['title'=>'Title','slug'=>'Slug','category'=>'Category','client'=>'Client','description'=>'Description','tools'=>'Tools used','results'=>'Results','featured'=>'Featured (1 or 0)'],'products'=>['name'=>'Name','slug'=>'Slug','price'=>'Price','category'=>'Category','description'=>'Description','availability'=>'Available (1 or 0)'],'services'=>['title'=>'Title','icon'=>'Icon','description'=>'Description'],'blogs'=>['title'=>'Title','slug'=>'Slug','category'=>'Category','excerpt'=>'Excerpt','content'=>'Article content','meta_title'=>'SEO title','meta_description'=>'SEO description'],'testimonials'=>['name'=>'Name','role'=>'Role','quote'=>'Quote','rating'=>'Rating'],'clients'=>['name'=>'Name','website'=>'Website'],'orders'=>['customer_name'=>'Customer name','phone'=>'Phone','address'=>'Address','items'=>'Items','total'=>'Total','status'=>'Status']];
if (!isset($definitions[$section])) redirect('/admin');
$item = null;
foreach (AdminResource::rows($section) as $row) if ((int) $row['id'] === $id) { $item = $row; break; }
if (!$item) redirect('/admin/' . $section);
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit | Crenova</title><link href="https://fonts.googleapis.com/css2?family=DM+Mono&family=DM+Sans:wght@400;600;700&family=Playfair+Display:ital,wght@0,500;1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?= url('assets/css/style.css') ?>"><link rel="stylesheet" href="<?= url('assets/css/additions.css') ?>"><link rel="stylesheet" href="<?= url('assets/css/bright-theme.css') ?>"></head>
<body class="admin-login"><a class="brand" href="<?= url('admin/' . $section) ?>"><img src="<?= url('assets/images/crenova-mark.svg') ?>" alt=""><span>CRENOVA<br><em>STUDIO</em></span></a>
<form class="login-card glass" method="post" enctype="multipart/form-data"><span class="eyebrow">Studio management</span><h1>Edit <i>item.</i></h1><input type="hidden" name="action" value="admin_save"><input type="hidden" name="resource" value="<?= e($section) ?>"><input type="hidden" name="id" value="<?= e($item['id']) ?>"><?= csrf_field() ?>
<?php foreach ($definitions[$section] as $name => $label): ?><label><?= e($label) ?><?php if (in_array($name, ['description','content','excerpt','quote','meta_description','address','items'], true)): ?><textarea name="<?= e($name) ?>" rows="3"><?= e($item[$name] ?? '') ?></textarea><?php else: ?><input name="<?= e($name) ?>" value="<?= e($item[$name] ?? '') ?>"><?php endif; ?></label><?php endforeach; ?>
<?php if (in_array($section, ['projects','products'], true)): ?><label>Replace image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><?php endif; ?><button class="button primary">Save changes <b>↗</b></button></form></body></html>
